name: aulataller
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  equatable: ^1.2.0
  flutter_bloc: ^4.0.0
  mockito: ^4.1.1
  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  get_it: ^5.0.6
  formz: ^0.3.2
  flutter_svg: ^0.19.1
  url_launcher: ^5.4.11
  flutter_staggered_grid_view: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/icons/instagram.svg
    - assets/icons/facebook.svg
    - assets/icons/aula_abierta.svg
    - assets/icons/sabios_al_gratin.svg
    - assets/icons/psicopedagogico.svg
    - assets/icons/analytics.svg
    - assets/icons/form.svg
    - assets/icons/search.svg
    - assets/icons/accountInfo.svg
    - assets/icons/asistence.svg
    - assets/icons/valoration.svg
    - assets/icons/log-out.svg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Nunito/Nunito-Black.ttf
          weight: 900
        - asset: fonts/Nunito/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Mukta
      fonts:
        - asset: fonts/Mukta/Mukta-ExtraLight.ttf
          weight: 200
        - asset: fonts/Mukta/Mukta-Light.ttf
          weight: 300
        - asset: fonts/Mukta/Mukta-Regular.ttf
          weight: 400
        - asset: fonts/Mukta/Mukta-Medium.ttf
          weight: 500
        - asset: fonts/Mukta/Mukta-SemiBold.ttf
          weight: 600
        - asset: fonts/Mukta/Mukta-Bold.ttf
          weight: 700
        - asset: fonts/Mukta/Mukta-ExtraBold.ttf
          weight: 800
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
